# 정규식 설장 파일 경로 지정
file_regex : config.praw

# 작업 스레드 개수 지정(고루틴)
work_thread : 200

# 파싱할 필드 지정이며, 
# 첫번째 키는 사용자 지정 이름이며, 
# 두번째 값은 file 에서 지정한 정규식 설정의 라인 수를 의미한다 
field_tag : 
        0 : ${frame_index} 
        1 : ${src_ip} 
        2 : ${dst_ip}
        3 : ${nf:version}
        4 : ${nf:sysuptime}
        5 : ${nf:flowset}
        6 : ${nf:src_ip}
        7 : ${nf:dst_ip}
        8 : ${nf:protocol}
        9 : ${nf:src_port}
        10 : ${nf:dst_port} 
        11 : ${nf:if_in}
        12 : ${nf:if_out}
        13 : ${nf:tcp_flags} 
        14 : ${nf:bytes}
        15 : ${nf:packets} 

# 읽어 들일 파일명 경로
in_file : test.txt
# 결과 저장할 파일명 경로
out_file : result.txt

# 저장 시 지정한 필드 형태로 라인별 저장할 포맷을 지정
#format : ${frame_index}-${nf:flowset},${src_ip}|${nf:sysuptime}Z-${nf:src_ip},${nf:dst_ip},${nf:src_port},${nf:dst_port},${nf:protocol},${nf:tcp_flags},${nf:if_in},${nf:if_out},${nf:bytes},${nf:packets}
format : ${src_ip}|Z-${nf:src_ip},${nf:dst_ip},${nf:src_port},${nf:dst_port},${nf:protocol},${nf:tcp_flags},${nf:if_in},${nf:if_out},${nf:bytes},${nf:packets},0,0

# milisecond
line_task_sleep : 10